# Generated by Django 4.2.23 on 2025-10-27 18:29

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="EmailLog",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("is_deleted", models.BooleanField(default=False)),
                ("deleted_at", models.DateTimeField(blank=True, null=True)),
                ("email_address", models.EmailField(max_length=254)),
                ("message_id", models.CharField(blank=True, max_length=100)),
                ("bounce_reason", models.CharField(blank=True, max_length=200)),
            ],
            options={
                "abstract": False,
            },
        ),
        migrations.CreateModel(
            name="Notification",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("is_deleted", models.BooleanField(default=False)),
                ("deleted_at", models.DateTimeField(blank=True, null=True)),
                ("subject", models.CharField(blank=True, max_length=200)),
                ("message", models.TextField()),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("PENDING", "Pending"),
                            ("SENT", "Sent"),
                            ("DELIVERED", "Delivered"),
                            ("FAILED", "Failed"),
                            ("READ", "Read"),
                        ],
                        default="PENDING",
                        max_length=10,
                    ),
                ),
                (
                    "channel",
                    models.CharField(
                        choices=[
                            ("SMS", "SMS"),
                            ("EMAIL", "Email"),
                            ("PUSH", "Push Notification"),
                            ("IN_APP", "In-App Notification"),
                        ],
                        max_length=10,
                    ),
                ),
                ("sent_at", models.DateTimeField(blank=True, null=True)),
                ("delivered_at", models.DateTimeField(blank=True, null=True)),
                ("read_at", models.DateTimeField(blank=True, null=True)),
                (
                    "external_id",
                    models.CharField(
                        blank=True, help_text="ID from external service", max_length=100
                    ),
                ),
                ("error_message", models.TextField(blank=True)),
                (
                    "context_data",
                    models.JSONField(
                        default=dict,
                        help_text="Additional context for the notification",
                    ),
                ),
            ],
            options={
                "ordering": ["-created_at"],
            },
        ),
        migrations.CreateModel(
            name="NotificationTemplate",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("is_deleted", models.BooleanField(default=False)),
                ("deleted_at", models.DateTimeField(blank=True, null=True)),
                ("name", models.CharField(max_length=100)),
                (
                    "notification_type",
                    models.CharField(
                        choices=[
                            ("ORDER_CREATED", "Order Created"),
                            ("ORDER_CONFIRMED", "Order Confirmed"),
                            ("ORDER_SHIPPED", "Order Shipped"),
                            ("ORDER_DELIVERED", "Order Delivered"),
                            ("ORDER_CANCELLED", "Order Cancelled"),
                            ("PAYMENT_RECEIVED", "Payment Received"),
                            ("PAYMENT_FAILED", "Payment Failed"),
                            ("PRODUCT_APPROVED", "Product Approved"),
                            ("PRODUCT_REJECTED", "Product Rejected"),
                            ("ACCOUNT_VERIFIED", "Account Verified"),
                            ("PRICE_ALERT", "Price Alert"),
                            ("CUSTOM", "Custom Message"),
                        ],
                        max_length=20,
                    ),
                ),
                (
                    "channel",
                    models.CharField(
                        choices=[
                            ("SMS", "SMS"),
                            ("EMAIL", "Email"),
                            ("PUSH", "Push Notification"),
                            ("IN_APP", "In-App Notification"),
                        ],
                        max_length=10,
                    ),
                ),
                (
                    "subject_template",
                    models.CharField(
                        blank=True, help_text="For email notifications", max_length=200
                    ),
                ),
                (
                    "message_template",
                    models.TextField(
                        help_text="Use {variable_name} for dynamic content"
                    ),
                ),
                ("is_active", models.BooleanField(default=True)),
            ],
        ),
        migrations.CreateModel(
            name="PushNotificationLog",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("is_deleted", models.BooleanField(default=False)),
                ("deleted_at", models.DateTimeField(blank=True, null=True)),
                ("device_token", models.CharField(max_length=255)),
                (
                    "platform",
                    models.CharField(
                        choices=[("IOS", "iOS"), ("ANDROID", "Android")], max_length=10
                    ),
                ),
                ("message_id", models.CharField(blank=True, max_length=100)),
            ],
            options={
                "abstract": False,
            },
        ),
        migrations.CreateModel(
            name="SMSLog",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("is_deleted", models.BooleanField(default=False)),
                ("deleted_at", models.DateTimeField(blank=True, null=True)),
                ("phone_number", models.CharField(max_length=20)),
                ("message_id", models.CharField(blank=True, max_length=100)),
                (
                    "cost",
                    models.DecimalField(
                        blank=True, decimal_places=4, max_digits=10, null=True
                    ),
                ),
                ("status_code", models.CharField(blank=True, max_length=10)),
                ("network_code", models.CharField(blank=True, max_length=10)),
            ],
            options={
                "abstract": False,
            },
        ),
        migrations.CreateModel(
            name="UserNotificationSettings",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("is_deleted", models.BooleanField(default=False)),
                ("deleted_at", models.DateTimeField(blank=True, null=True)),
                ("sms_enabled", models.BooleanField(default=True)),
                ("sms_order_updates", models.BooleanField(default=True)),
                ("sms_payment_updates", models.BooleanField(default=True)),
                ("sms_marketing", models.BooleanField(default=False)),
                ("email_enabled", models.BooleanField(default=True)),
                ("email_order_updates", models.BooleanField(default=True)),
                ("email_payment_updates", models.BooleanField(default=True)),
                ("email_marketing", models.BooleanField(default=True)),
                ("email_newsletter", models.BooleanField(default=True)),
                ("push_enabled", models.BooleanField(default=True)),
                ("push_order_updates", models.BooleanField(default=True)),
                ("push_payment_updates", models.BooleanField(default=True)),
                ("push_marketing", models.BooleanField(default=False)),
                ("in_app_enabled", models.BooleanField(default=True)),
            ],
            options={
                "abstract": False,
            },
        ),
    ]
