# Generated by Django 4.2.23 on 2025-10-28 00:17

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("users", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="user",
            name="phone_number",
            field=models.CharField(
                blank=True,
                max_length=15,
                null=True,
                unique=True,
                validators=[
                    django.core.validators.RegexValidator(
                        message="Phone number must be in format: '+254712345678'",
                        regex="^\\+254[17]\\d{8}$",
                    )
                ],
            ),
        ),
    ]
